#!/usr/bin/env python3
"""Generate sw.js with a versioned cache list of this repo's assets.

Usage: make-sw.py [version]
  version defaults to the current UTC timestamp (YYYYMMDD-HHMM).
Run after editing app files, before committing, so the service worker
cache-busts. This repo never carries a CNAME (custom domain is
production-only); do not add one.
"""
import datetime
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))

# User-facing app version shown in Settings → About ("Cruciferous Greens
# Workout · vX"). Bump this whenever a build ships user-visible changes.
APP_VERSION = "1.49"

now = datetime.datetime.now(datetime.timezone.utc)
# Seconds in the stamp (user 2026-09-11): two builds in the same minute
# produced byte-identical sw.js, which the browser treats as "no update".
version = sys.argv[1] if len(sys.argv) > 1 else now.strftime("%Y%m%d-%H%M%S")

# Build metadata consumed by Settings → About ("Last updated"). Written before
# the asset scan so it lands in the service worker cache list too.
build_info = f"""/* Generated by make-sw.py; do not hand-edit. */
window.BUILD_INFO={{appVersion:"{APP_VERSION}",build:"{version}",builtAt:"{now.isoformat()}"}};
"""
with open(os.path.join(ROOT, "assets", "js", "build-info.js"), "w") as f:
    f.write(build_info)

assets = [
    "./",
    "index.html",
    "manifest.webmanifest",
    "icon-180.png",
    "icon-192.png",
    "icon-512.png",
    "og-card.png",
    "share-card-home-1200.png",
    "assets/styles.css",
    "data/exercises-db.js",
    "data/exercise-aliases.js",
    "data/sasha-male-body.svg",
]
js_dir = os.path.join(ROOT, "assets", "js")
for f in sorted(os.listdir(js_dir)):
    if f.endswith(".js"):
        assets.append(f"assets/js/{f}")

# v1.005: the unit-test harness lives in tests/ but must never ship to
# phones — neither in the SW cache nor (via _config.yml's Jekyll exclude)
# in the Pages deployment. Fail loudly instead of caching it by accident.
# v1.014 (#177): 404.html (the GitHub Pages SPA fallback for /s/<slug>
# short-share links) is DELIBERATELY absent from this list. The host serves
# it for unknown paths; precaching it as an app-shell asset risks the SW
# serving stale redirect logic, and the fetch handler already falls back to
# network for uncached navigations (a 404 response is never cached since
# only res.ok responses are put). Do not add it here.
leaked = [a for a in assets if a == "tests" or a.startswith("tests/")]
if leaked:
    sys.stderr.write(
        f'make-sw.py: refusing to cache test files: {", ".join(leaked)}\n'
    )
    sys.exit(1)

# #99 B24: the SW cache auto-scans assets/js, but index.html hand-orders the
# <script> tags (load order is load-bearing — do NOT let this generate the
# tags). Validate that both lists name the SAME set of files, and fail loudly
# on any mismatch instead of shipping cached-but-unloaded or
# loaded-but-uncached JS. data/exercises-db.js is hand-listed above and out
# of this check's scope.
with open(os.path.join(ROOT, "index.html")) as f:
    script_tags = re.findall(r'<script\s+src=["\']([^"\']+)["\']', f.read())
tagged_js = {s[len("assets/js/"):] for s in script_tags if s.startswith("assets/js/")}
scanned_js = {f for f in os.listdir(js_dir) if f.endswith(".js")}
not_loaded = sorted(scanned_js - tagged_js)
not_on_disk = sorted(tagged_js - scanned_js)
if not_loaded or not_on_disk:
    msg = ["make-sw.py: asset manifest mismatch with index.html script tags:"]
    if not_loaded:
        msg.append(f"  in assets/js but no <script> tag: {', '.join(not_loaded)}")
    if not_on_disk:
        msg.append(f"  <script> tag but not in assets/js: {', '.join(not_on_disk)}")
    msg.append("Fix index.html's script tags (load order is hand-tuned), then re-run.")
    sys.stderr.write("\n".join(msg) + "\n")
    sys.exit(1)

asset_lines = ",\n    ".join(f'"{a}"' for a in assets)

sw = f"""/* Workout App service worker — offline-first app shell cache.
 * Generated by make-sw.py; do not hand-edit (version {version}). */
const SW_VERSION = "{version}";
const CACHE_NAME = "workout-app-" + SW_VERSION;
const ASSETS = [
    {asset_lines}
];

self.addEventListener("install", (event) => {{
  event.waitUntil(
    caches.open(CACHE_NAME)
      /* Per-asset add under allSettled (user 2026-09-11): addAll is
         all-or-nothing, so one flaky fetch on cellular silently pinned the
         old version. A partial install is safe — the fetch handler falls
         back to network on a cache miss. cache:'reload' bypasses the HTTP
         cache (GitHub Pages sends max-age=600), so a fast follow-up build
         can't precache stale assets. */
      .then((cache) =>
        Promise.allSettled(
          ASSETS.map((u) => cache.add(new Request(u, {{cache: "reload"}})))
        )
      )
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith("workout-app-") && k !== CACHE_NAME)
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then(
      (hit) =>
        hit ||
        fetch(event.request)
          .then((res) => {{
            if (res.ok) {{
              const copy = res.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
            }}
            return res;
          }})
          .catch((err) => {{
            /* The index.html fallback is for navigations only (user
               2026-09-11): a failed JS/data fetch resolving with HTML and
               status 200 broke version probes and confused debugging. */
            if (event.request.mode === "navigate") return caches.match("index.html");
            throw err;
          }})
    )
  );
}});
"""

with open(os.path.join(ROOT, "sw.js"), "w") as f:
    f.write(sw)
print(f"wrote sw.js version {version} with {len(assets)} assets")
