#!/usr/bin/env python3
"""Generate sw.js with a versioned cache list of this repo's assets.

Usage: make-sw.py [version]
  version defaults to the current UTC timestamp (YYYYMMDD-HHMM).
Run after editing app files, before committing, so the service worker
cache-busts. This repo never carries a CNAME (custom domain is
production-only); do not add one.
"""
import datetime
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))

# User-facing app version shown in Settings → About ("Cruciferous Greens
# Workout · vX"). Bump this whenever a build ships user-visible changes.
APP_VERSION = "0.6"

now = datetime.datetime.now(datetime.timezone.utc)
version = sys.argv[1] if len(sys.argv) > 1 else now.strftime("%Y%m%d-%H%M")

# Build metadata consumed by Settings → About ("Last updated"). Written before
# the asset scan so it lands in the service worker cache list too.
build_info = f"""/* Generated by make-sw.py; do not hand-edit. */
window.BUILD_INFO={{appVersion:"{APP_VERSION}",build:"{version}",builtAt:"{now.isoformat()}"}};
"""
with open(os.path.join(ROOT, "assets", "js", "build-info.js"), "w") as f:
    f.write(build_info)

assets = [
    "./",
    "index.html",
    "manifest.webmanifest",
    "icon-180.png",
    "icon-512.png",
    "assets/styles.css",
    "data/exercises-db.js",
    "data/sasha-male-body.svg",
]
js_dir = os.path.join(ROOT, "assets", "js")
for f in sorted(os.listdir(js_dir)):
    if f.endswith(".js"):
        assets.append(f"assets/js/{f}")

asset_lines = ",\n    ".join(f'"{a}"' for a in assets)

sw = f"""/* Workout App service worker — offline-first app shell cache.
 * Generated by make-sw.py; do not hand-edit (version {version}). */
const SW_VERSION = "{version}";
const CACHE_NAME = "workout-app-" + SW_VERSION;
const ASSETS = [
    {asset_lines}
];

self.addEventListener("install", (event) => {{
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith("workout-app-") && k !== CACHE_NAME)
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then(
      (hit) =>
        hit ||
        fetch(event.request)
          .then((res) => {{
            if (res.ok) {{
              const copy = res.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
            }}
            return res;
          }})
          .catch(() => caches.match("index.html"))
    )
  );
}});
"""

with open(os.path.join(ROOT, "sw.js"), "w") as f:
    f.write(sw)
print(f"wrote sw.js version {version} with {len(assets)} assets")
