/* Workout App service worker — offline-first app shell cache.
 * Generated by make-sw.py; do not hand-edit (version 20260912-145257). */
const SW_VERSION = "20260912-145257";
const CACHE_NAME = "workout-app-" + SW_VERSION;
const ASSETS = [
    "./",
    "index.html",
    "manifest.webmanifest",
    "icon-180.png",
    "icon-512.png",
    "assets/styles.css",
    "data/exercises-db.js",
    "data/sasha-male-body.svg",
    "assets/js/app-bootstrap.js",
    "assets/js/app-updates.js",
    "assets/js/build-info.js",
    "assets/js/catalog.js",
    "assets/js/csv-import.js",
    "assets/js/custom-exercises.js",
    "assets/js/dashboard-stats.js",
    "assets/js/exercise-data.js",
    "assets/js/exercise-detail.js",
    "assets/js/exercise-library.js",
    "assets/js/navigation.js",
    "assets/js/persistence.js",
    "assets/js/program-templates.js",
    "assets/js/programs.js",
    "assets/js/progression.js",
    "assets/js/saved-workouts.js",
    "assets/js/set-tags.js",
    "assets/js/share-codec.js",
    "assets/js/share.js",
    "assets/js/state.js",
    "assets/js/supersets.js",
    "assets/js/sync-account-ui.js",
    "assets/js/sync-adapter.js",
    "assets/js/sync-auth.js",
    "assets/js/sync-engine.js",
    "assets/js/utilities.js",
    "assets/js/workout-builder.js",
    "assets/js/workout-editor.js",
    "assets/js/workout-history.js"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      /* Per-asset add under allSettled (user 2026-09-11): addAll is
         all-or-nothing, so one flaky fetch on cellular silently pinned the
         old version. A partial install is safe — the fetch handler falls
         back to network on a cache miss. cache:'reload' bypasses the HTTP
         cache (GitHub Pages sends max-age=600), so a fast follow-up build
         can't precache stale assets. */
      .then((cache) =>
        Promise.allSettled(
          ASSETS.map((u) => cache.add(new Request(u, {cache: "reload"})))
        )
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith("workout-app-") && k !== CACHE_NAME)
            .map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then(
      (hit) =>
        hit ||
        fetch(event.request)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
            }
            return res;
          })
          .catch((err) => {
            /* The index.html fallback is for navigations only (user
               2026-09-11): a failed JS/data fetch resolving with HTML and
               status 200 broke version probes and confused debugging. */
            if (event.request.mode === "navigate") return caches.match("index.html");
            throw err;
          })
    )
  );
});
